Food.create!(name: "Vegetables")
Food.create!(name: "Rosted Vegetables")
Food.create!(name: "Soft Cheese")
Food.create!(name: "Hard Cheese")
Food.create!(name: "Starches")
Food.create!(name: "Fish")
Food.create!(name: "Rich Fish")
Food.create!(name: "White Meat")
Food.create!(name: "Red Meat")
Food.create!(name: "Cured Meat")
Food.create!(name: "Sweets")

Drink.create!(name: "Dry White Wine")
Drink.create!(name: "Sweet White Wine")
Drink.create!(name: "Rich White Wine")
Drink.create!(name: "Sparkling Wine")
Drink.create!(name: "Light Red Wine")
Drink.create!(name: "Medium Red Wine")
Drink.create!(name: "Bold Red Wine")
Drink.create!(name: "Dessert Wine")
Drink.create!(name: "Blond/Cream Ale")
Drink.create!(name: "British-Style Bitter")
Drink.create!(name: "Pale Ale")
Drink.create!(name: "Indian Pale Ale")
Drink.create!(name: "Double/Imperial IPA")
Drink.create!(name: "Amber/Red Ale")
Drink.create!(name: "Scotch Ale")
Drink.create!(name: "Brown Ale")
Drink.create!(name: "Abbey Dubbel")
Drink.create!(name: "Strong Golden Ale")
Drink.create!(name: "Strong Ale")
Drink.create!(name: "Barley Wine")
Drink.create!(name: "Dry Stout")
Drink.create!(name: "Porter")
Drink.create!(name: "Oatmeal Stout")
Drink.create!(name: "Imperial Stout")
Drink.create!(name: "American Wheat Ale")
Drink.create!(name: "Witbier")
Drink.create!(name: "Dunkelweizen")
Drink.create!(name: "Weizenbock")
Drink.create!(name: "Classic Pilsener")
Drink.create!(name: "Helles")
Drink.create!(name: "Oktoberfest,Vienna")
Drink.create!(name: "Dark Larger")
Drink.create!(name: "Pale Bock")
Drink.create!(name: "Doppelbock")


Pairing.create!(food_id: 1, drink_id: 1)
Pairing.create!(food_id: 2, drink_id: 1)
Pairing.create!(food_id: 6, drink_id: 1)
Pairing.create!(food_id: 3, drink_id: 2)
Pairing.create!(food_id: 4, drink_id: 2)
Pairing.create!(food_id: 10, drink_id: 2)
Pairing.create!(food_id: 11, drink_id: 2)
Pairing.create!(food_id: 3, drink_id: 3)
Pairing.create!(food_id: 5, drink_id: 3)
Pairing.create!(food_id: 6, drink_id: 3)
Pairing.create!(food_id: 7, drink_id: 3)
Pairing.create!(food_id: 8, drink_id: 3)
Pairing.create!(food_id: 1, drink_id: 4)
Pairing.create!(food_id: 3, drink_id: 4)
Pairing.create!(food_id: 4, drink_id: 4)
Pairing.create!(food_id: 5, drink_id: 4)
Pairing.create!(food_id: 6, drink_id: 4)
Pairing.create!(food_id: 2, drink_id: 5)
Pairing.create!(food_id: 5, drink_id: 5)
Pairing.create!(food_id: 7, drink_id: 5)
Pairing.create!(food_id: 8, drink_id: 5)
Pairing.create!(food_id: 10, drink_id: 5)
Pairing.create!(food_id: 2, drink_id: 6)
Pairing.create!(food_id: 4, drink_id: 6)
Pairing.create!(food_id: 5, drink_id: 6)
Pairing.create!(food_id: 6, drink_id: 6)
Pairing.create!(food_id: 7, drink_id: 6)
Pairing.create!(food_id: 8, drink_id: 6)
Pairing.create!(food_id: 4, drink_id: 7)
Pairing.create!(food_id: 8, drink_id: 7)
Pairing.create!(food_id: 9, drink_id: 7)
Pairing.create!(food_id: 3, drink_id: 8)
Pairing.create!(food_id: 5, drink_id: 8)
Pairing.create!(food_id: 10, drink_id: 8)
Pairing.create!(food_id: 11, drink_id: 8)
Pairing.create!(food_id: 1, drink_id: 9)
Pairing.create!(food_id: 8, drink_id: 9)
Pairing.create!(food_id: 10, drink_id: 9)
Pairing.create!(food_id: 3, drink_id: 10)
Pairing.create!(food_id: 6, drink_id: 10)
Pairing.create!(food_id: 8, drink_id: 10)
Pairing.create!(food_id: 4, drink_id: 11)
Pairing.create!(food_id: 9, drink_id: 11)
Pairing.create!(food_id: 9, drink_id: 12)
Pairing.create!(food_id: 11, drink_id: 12)
Pairing.create!(food_id: 8, drink_id: 13)
Pairing.create!(food_id: 9, drink_id: 13)
Pairing.create!(food_id: 6, drink_id: 14)
Pairing.create!(food_id: 8, drink_id: 14)
Pairing.create!(food_id: 6, drink_id: 15)
Pairing.create!(food_id: 9, drink_id: 15)
Pairing.create!(food_id: 9, drink_id: 16)
Pairing.create!(food_id: 10, drink_id: 16)
Pairing.create!(food_id: 5, drink_id: 17)
Pairing.create!(food_id: 9, drink_id: 17)
Pairing.create!(food_id: 7, drink_id: 18)
Pairing.create!(food_id: 8, drink_id: 18)
Pairing.create!(food_id: 2, drink_id: 19)
Pairing.create!(food_id: 9, drink_id: 19)
Pairing.create!(food_id: 3, drink_id: 20)
Pairing.create!(food_id: 4, drink_id: 20)
Pairing.create!(food_id: 11, drink_id: 20)
Pairing.create!(food_id: 7, drink_id: 21)
Pairing.create!(food_id: 9, drink_id: 21)
Pairing.create!(food_id: 4, drink_id: 22)
Pairing.create!(food_id: 7, drink_id: 22)
Pairing.create!(food_id: 8, drink_id: 22)
Pairing.create!(food_id: 5, drink_id: 23)
Pairing.create!(food_id: 9, drink_id: 23)
Pairing.create!(food_id: 2, drink_id: 24)
Pairing.create!(food_id: 3, drink_id: 24)
Pairing.create!(food_id: 10, drink_id: 24)
Pairing.create!(food_id: 1, drink_id: 25)
Pairing.create!(food_id: 2, drink_id: 25)
Pairing.create!(food_id: 5, drink_id: 25)
Pairing.create!(food_id: 6, drink_id: 26)
Pairing.create!(food_id: 7, drink_id: 26)
Pairing.create!(food_id: 1, drink_id: 27)
Pairing.create!(food_id: 8, drink_id: 27)
Pairing.create!(food_id: 9, drink_id: 28)
Pairing.create!(food_id: 10, drink_id: 28)
Pairing.create!(food_id: 6, drink_id: 29)
Pairing.create!(food_id: 7, drink_id: 29)
Pairing.create!(food_id: 8, drink_id: 29)
Pairing.create!(food_id: 1, drink_id: 30)
Pairing.create!(food_id: 2, drink_id: 30)
Pairing.create!(food_id: 5, drink_id: 30)
Pairing.create!(food_id: 8, drink_id: 31)
Pairing.create!(food_id: 10, drink_id: 31)
Pairing.create!(food_id: 8, drink_id: 32)
Pairing.create!(food_id: 9, drink_id: 32)
Pairing.create!(food_id: 10, drink_id: 32)
Pairing.create!(food_id: 8, drink_id: 33)
Pairing.create!(food_id: 9, drink_id: 33)
Pairing.create!(food_id: 4, drink_id: 34)
Pairing.create!(food_id: 5, drink_id: 34)
Pairing.create!(food_id: 8, drink_id: 34)# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
